#server:
#  port: 8081
swagger:
    groupName: mmm
    basePackage: com.zl.financial.controller
spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss.SSS
        time-zone: GMT+8
#    datasource:
#        url: jdbc:mysql://10.5.16.9:3306/manager?user=wch&password=wch123&useUnicode=true&characterEncoding=utf-8
    jpa:
        show-sql:true